[package]
name = "jester_script"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4.1"
chumsky = { version = "1.0.0-alpha.7", features = ["label"] }
eyre = "0.6.12"

[dev-dependencies]
glob = "0.3.1"
pretty_assertions = "1.4.0"
